NOME_DISC = '(?<=<th>Denominação</th><td>).*?(?=</td>)'
DEPARTAMENTO = '(?<=>Órgão</th><td class=\'col-lg-11 col-sm-11 col-xs-11\'>).*?(?=</td>)'
CODIGO = '(?<=<th>Código</th><td>).*?(?=</td>)'
NIVEL = '(?<=<th>Nível</th><td>).*?(?=</td>)'
VIGENCIA = '(?<=<th>Vigência</th><td>).*?(?=</td>)'
EMENTA = '(?<=<th>Ementa</th><td><p align=justify>).*?(?=</p></td>)'
PROGRAMA = '(?<=<th>Programa</th><td><p align=justify>).*?(?=</p></td>)'
BIBLIOGRAFIA = '(?<=<th>Bibliografia</th><td><p align=justify>).*?(?=</p></td>)'
PRE_REQUISITOS = '(?<=<th>Pré-requisitos</th><td>).*?(?=</td>)'
#DEPARTAMENTO_PRE_REQ = '(?<=<small> ).*?(?= </small>)'
CODIGO_PRE_REQ = '(?<=<strong> ).*?(?= </strong>)'
NOME_DISC_PRE_REQ = '(?<=</strong>).*?(?= </a>)'
E_PRE_REQ = '<strong> E </strong><br>'
OU_PRE_REQ = '<strong> OU </strong>'
ENTER = '<Return>'
TEMPO_EXCEDIDO = 'Página do MatriculaWeb não responde...'
DISCIPLINA_NAO_ENCONTRADA = 'MATTER NOT FOUND'
ATIVADO = 1
DESATIVADO = 0